# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/game_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/game_service.proto\x12\x03rps\"!\n\x0c\x43heckRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"0\n\rCheckResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0e\n\x06\x65xists\x18\x02 \x01(\x08\"8\n\rCreateRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x14\n\x0cis_join_only\x18\x02 \x01(\x08\"2\n\x0cStateRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\"A\n\x0bMoveRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\x12\x0e\n\x06\x63hoice\x18\x03 \x01(\t\"1\n\x0b\x45xitRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\"\x1f\n\x0c\x45xitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xef\x01\n\x0cGameResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0f\n\x07player1\x18\x02 \x01(\t\x12\x0f\n\x07player2\x18\x03 \x01(\t\x12\x16\n\x0eplayer1_choice\x18\x04 \x01(\t\x12\x16\n\x0eplayer2_choice\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x19\n\x11\x63urrent_player_id\x18\x07 \x01(\t\x12\r\n\x05\x65rror\x18\x08 \x01(\t\x12\x15\n\rplayer1_score\x18\t \x01(\x05\x12\x15\n\rplayer2_score\x18\n \x01(\x05\x12\x14\n\x0cround_result\x18\x0b \x01(\t2\xc0\x02\n\x0bGameService\x12\x33\n\nCreateGame\x12\x12.rps.CreateRequest\x1a\x11.rps.GameResponse\x12/\n\x08MakeMove\x12\x10.rps.MoveRequest\x1a\x11.rps.GameResponse\x12\x30\n\x08GetState\x12\x11.rps.StateRequest\x1a\x11.rps.GameResponse\x12\x35\n\x0c\x43heckSession\x12\x11.rps.CheckRequest\x1a\x12.rps.CheckResponse\x12\x31\n\tResetGame\x12\x11.rps.StateRequest\x1a\x11.rps.GameResponse\x12/\n\x08\x45xitGame\x12\x10.rps.ExitRequest\x1a\x11.rps.ExitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.game_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKREQUEST']._serialized_start=34
  _globals['_CHECKREQUEST']._serialized_end=67
  _globals['_CHECKRESPONSE']._serialized_start=69
  _globals['_CHECKRESPONSE']._serialized_end=117
  _globals['_CREATEREQUEST']._serialized_start=119
  _globals['_CREATEREQUEST']._serialized_end=175
  _globals['_STATEREQUEST']._serialized_start=177
  _globals['_STATEREQUEST']._serialized_end=227
  _globals['_MOVEREQUEST']._serialized_start=229
  _globals['_MOVEREQUEST']._serialized_end=294
  _globals['_EXITREQUEST']._serialized_start=296
  _globals['_EXITREQUEST']._serialized_end=345
  _globals['_EXITRESPONSE']._serialized_start=347
  _globals['_EXITRESPONSE']._serialized_end=378
  _globals['_GAMERESPONSE']._serialized_start=381
  _globals['_GAMERESPONSE']._serialized_end=620
  _globals['_GAMESERVICE']._serialized_start=623
  _globals['_GAMESERVICE']._serialized_end=943
# @@protoc_insertion_point(module_scope)
