# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import game_service_pb2 as protos_dot_game__service__pb2


class GameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/rps.GameService/CreateGame',
                request_serializer=protos_dot_game__service__pb2.CreateRequest.SerializeToString,
                response_deserializer=protos_dot_game__service__pb2.GameResponse.FromString,
                )
        self.MakeMove = channel.unary_unary(
                '/rps.GameService/MakeMove',
                request_serializer=protos_dot_game__service__pb2.MoveRequest.SerializeToString,
                response_deserializer=protos_dot_game__service__pb2.GameResponse.FromString,
                )
        self.GetState = channel.unary_unary(
                '/rps.GameService/GetState',
                request_serializer=protos_dot_game__service__pb2.StateRequest.SerializeToString,
                response_deserializer=protos_dot_game__service__pb2.GameResponse.FromString,
                )
        self.CheckSession = channel.unary_unary(
                '/rps.GameService/CheckSession',
                request_serializer=protos_dot_game__service__pb2.CheckRequest.SerializeToString,
                response_deserializer=protos_dot_game__service__pb2.CheckResponse.FromString,
                )
        self.ResetGame = channel.unary_unary(
                '/rps.GameService/ResetGame',
                request_serializer=protos_dot_game__service__pb2.StateRequest.SerializeToString,
                response_deserializer=protos_dot_game__service__pb2.GameResponse.FromString,
                )
        self.ExitGame = channel.unary_unary(
                '/rps.GameService/ExitGame',
                request_serializer=protos_dot_game__service__pb2.ExitRequest.SerializeToString,
                response_deserializer=protos_dot_game__service__pb2.ExitResponse.FromString,
                )


class GameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=protos_dot_game__service__pb2.CreateRequest.FromString,
                    response_serializer=protos_dot_game__service__pb2.GameResponse.SerializeToString,
            ),
            'MakeMove': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeMove,
                    request_deserializer=protos_dot_game__service__pb2.MoveRequest.FromString,
                    response_serializer=protos_dot_game__service__pb2.GameResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=protos_dot_game__service__pb2.StateRequest.FromString,
                    response_serializer=protos_dot_game__service__pb2.GameResponse.SerializeToString,
            ),
            'CheckSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSession,
                    request_deserializer=protos_dot_game__service__pb2.CheckRequest.FromString,
                    response_serializer=protos_dot_game__service__pb2.CheckResponse.SerializeToString,
            ),
            'ResetGame': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetGame,
                    request_deserializer=protos_dot_game__service__pb2.StateRequest.FromString,
                    response_serializer=protos_dot_game__service__pb2.GameResponse.SerializeToString,
            ),
            'ExitGame': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitGame,
                    request_deserializer=protos_dot_game__service__pb2.ExitRequest.FromString,
                    response_serializer=protos_dot_game__service__pb2.ExitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rps.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rps.GameService/CreateGame',
            protos_dot_game__service__pb2.CreateRequest.SerializeToString,
            protos_dot_game__service__pb2.GameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakeMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rps.GameService/MakeMove',
            protos_dot_game__service__pb2.MoveRequest.SerializeToString,
            protos_dot_game__service__pb2.GameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rps.GameService/GetState',
            protos_dot_game__service__pb2.StateRequest.SerializeToString,
            protos_dot_game__service__pb2.GameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rps.GameService/CheckSession',
            protos_dot_game__service__pb2.CheckRequest.SerializeToString,
            protos_dot_game__service__pb2.CheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rps.GameService/ResetGame',
            protos_dot_game__service__pb2.StateRequest.SerializeToString,
            protos_dot_game__service__pb2.GameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExitGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rps.GameService/ExitGame',
            protos_dot_game__service__pb2.ExitRequest.SerializeToString,
            protos_dot_game__service__pb2.ExitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
