# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/orm.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/orm.proto\x12\x03rps\"(\n\x13\x43heckSessionRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"7\n\x14\x43heckSessionResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0e\n\x06\x65xists\x18\x02 \x01(\x08\"5\n\x0f\x45xitGameRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\"#\n\x10\x45xitGameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0bLoadRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"8\n\x0cLoadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x04game\x18\x02 \x01(\x0b\x32\t.rps.Game\"7\n\x0bSaveRequest\x12\x17\n\x04game\x18\x01 \x01(\x0b\x32\t.rps.Game\x12\x0f\n\x07game_id\x18\x02 \x01(\t\"\x1f\n\x0cSaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x96\x01\n\x04Game\x12\x0f\n\x07player1\x18\x01 \x01(\t\x12\x0f\n\x07player2\x18\x02 \x01(\t\x12\x16\n\x0eplayer1_choice\x18\x03 \x01(\t\x12\x16\n\x0eplayer2_choice\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x15\n\rplayer1_score\x18\x06 \x01(\x05\x12\x15\n\rplayer2_score\x18\x07 \x01(\x05\x32\xdd\x01\n\x03Orm\x12\x43\n\x0c\x43heckSession\x12\x18.rps.CheckSessionRequest\x1a\x19.rps.CheckSessionResponse\x12\x37\n\x08\x45xitGame\x12\x14.rps.ExitGameRequest\x1a\x15.rps.ExitGameResponse\x12+\n\x04Load\x12\x10.rps.LoadRequest\x1a\x11.rps.LoadResponse\x12+\n\x04Save\x12\x10.rps.SaveRequest\x1a\x11.rps.SaveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.orm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKSESSIONREQUEST']._serialized_start=25
  _globals['_CHECKSESSIONREQUEST']._serialized_end=65
  _globals['_CHECKSESSIONRESPONSE']._serialized_start=67
  _globals['_CHECKSESSIONRESPONSE']._serialized_end=122
  _globals['_EXITGAMEREQUEST']._serialized_start=124
  _globals['_EXITGAMEREQUEST']._serialized_end=177
  _globals['_EXITGAMERESPONSE']._serialized_start=179
  _globals['_EXITGAMERESPONSE']._serialized_end=214
  _globals['_LOADREQUEST']._serialized_start=216
  _globals['_LOADREQUEST']._serialized_end=246
  _globals['_LOADRESPONSE']._serialized_start=248
  _globals['_LOADRESPONSE']._serialized_end=304
  _globals['_SAVEREQUEST']._serialized_start=306
  _globals['_SAVEREQUEST']._serialized_end=361
  _globals['_SAVERESPONSE']._serialized_start=363
  _globals['_SAVERESPONSE']._serialized_end=394
  _globals['_GAME']._serialized_start=397
  _globals['_GAME']._serialized_end=547
  _globals['_ORM']._serialized_start=550
  _globals['_ORM']._serialized_end=771
# @@protoc_insertion_point(module_scope)
