# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import orm_pb2 as protos_dot_orm__pb2


class OrmStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckSession = channel.unary_unary(
                '/rps.Orm/CheckSession',
                request_serializer=protos_dot_orm__pb2.CheckSessionRequest.SerializeToString,
                response_deserializer=protos_dot_orm__pb2.CheckSessionResponse.FromString,
                )
        self.ExitGame = channel.unary_unary(
                '/rps.Orm/ExitGame',
                request_serializer=protos_dot_orm__pb2.ExitGameRequest.SerializeToString,
                response_deserializer=protos_dot_orm__pb2.ExitGameResponse.FromString,
                )
        self.Load = channel.unary_unary(
                '/rps.Orm/Load',
                request_serializer=protos_dot_orm__pb2.LoadRequest.SerializeToString,
                response_deserializer=protos_dot_orm__pb2.LoadResponse.FromString,
                )
        self.Save = channel.unary_unary(
                '/rps.Orm/Save',
                request_serializer=protos_dot_orm__pb2.SaveRequest.SerializeToString,
                response_deserializer=protos_dot_orm__pb2.SaveResponse.FromString,
                )


class OrmServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Load(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSession,
                    request_deserializer=protos_dot_orm__pb2.CheckSessionRequest.FromString,
                    response_serializer=protos_dot_orm__pb2.CheckSessionResponse.SerializeToString,
            ),
            'ExitGame': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitGame,
                    request_deserializer=protos_dot_orm__pb2.ExitGameRequest.FromString,
                    response_serializer=protos_dot_orm__pb2.ExitGameResponse.SerializeToString,
            ),
            'Load': grpc.unary_unary_rpc_method_handler(
                    servicer.Load,
                    request_deserializer=protos_dot_orm__pb2.LoadRequest.FromString,
                    response_serializer=protos_dot_orm__pb2.LoadResponse.SerializeToString,
            ),
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=protos_dot_orm__pb2.SaveRequest.FromString,
                    response_serializer=protos_dot_orm__pb2.SaveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rps.Orm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Orm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rps.Orm/CheckSession',
            protos_dot_orm__pb2.CheckSessionRequest.SerializeToString,
            protos_dot_orm__pb2.CheckSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExitGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rps.Orm/ExitGame',
            protos_dot_orm__pb2.ExitGameRequest.SerializeToString,
            protos_dot_orm__pb2.ExitGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rps.Orm/Load',
            protos_dot_orm__pb2.LoadRequest.SerializeToString,
            protos_dot_orm__pb2.LoadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rps.Orm/Save',
            protos_dot_orm__pb2.SaveRequest.SerializeToString,
            protos_dot_orm__pb2.SaveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
